### ISSUE TITLE
Unavailable link to dataset of complex head pose

### ISSUE THREAD

**Issue by shengzhelyu65** [nesl/auritus#1]
Hi,

Firstly I want to appreciate this amazing project you have done! Thanks for sharing the dataset in public.

I have been trying to access the "Complex Head Pose" dataset shared via Google Drive. Unfortunately, the current link appears to be unavailable. I kindly request that the dataset's owners consider re-uploading the dataset or provide an alternative means of access. Thank you for your assistance in addressing this request! The dataset will only be used in academic use.

**Comment by swapnilsayansaha** [comment]
Ya you are right. I have to check to see if the complex head pose dataset is available anywhere else.

**Comment by swapnilsayansaha** [comment]
We found the dataset and will reupload in a day or two.

**Comment by shengzhelyu65** [comment]
Thanks again for your sincere work!

**Comment by swapnilsayansaha** [comment]
@shengzhelyu65 we have uploaded at minimum the csv files for the complex headpose. .tak files are present for subjects 1-15. We will upload the .tak files for subjects 15-45 soon. We will also upload the .c3d files and .csv file with TD for all subjects soon. Please find the dataset here: https://drive.google.com/drive/folders/1sTeXlavakNSEeR-MK6vFU1LT3X-M3_hM?usp=sharing

**Comment by shengzhelyu65** [comment]
Thank you for your assistance!

**Comment by swapnilsayansaha** [comment]
We uploaded all the necessary files. They should be in the drive link now. For subjects 1-15 we will upload the c3d and td csv files by tomorrow. Closing this issue
