### ISSUE TITLE
I cannot access the Head Pose dataset

### ISSUE THREAD

**Issue by ubi-hiro** [nesl/auritus#2]
Hello,

The dataset you provide is highly valuable, and I am grateful for your offering of it.

I am currently conducting research on head tracking, and I attempted to use this dataset for academic purposes. However, I am unable to access the links to the "Simple Head Pose" and "Complex Head Pose" datasets.

Would it be possible for you to fix this issue?

If the problem is on my end, I apologize for the inconvenience.

**Comment by swapnilsayansaha** [comment]
Complex: https://drive.google.com/drive/folders/0B8mK5vcy110Hfmptd2twTFhqbWU2VDEybWRlWTdqSkNnNG54NWJkWElHTVVwd2NsWjdHN2M?resourcekey=0-d3JqqpXQXslSqVLQB6kfjg

Simple: https://drive.google.com/file/d/1Wx-c6h-N5NrNOSm07Rldci6UVJ7INm9k/view?usp=drivesdk

**Comment by ubi-hiro** [comment]
Thank you for your response！
